password = "12345"
supabase_url = "https://aidvdbvklgbjkvtqvexg.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpZHZkYnZrbGdiamt2dHF2ZXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA5NTE4NzcsImV4cCI6MjAyNjUyNzg3N30.GfU5w56CFzSRU4fc4TaMwZOJGZjoFkzx20KFqeyt2jA"

[passwords]
username = "user123"
